name: CI Master

on:
  push:
    tags: 
      - 'rel-*'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.4
        

      - name: Resolve dependencies
        working-directory: ./backend
        run: npm ci

      - name: Execute ESLint checks
        working-directory: ./backend
        run: npm run eslint:check

      - name: Execute unit tests
        working-directory: ./backend
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: italodea/bancario:latest

